name: myown

on:
  push:
    branches:
    - main

env:
  s3: my-own-aws742
  region: ap-south-1
  AWS_DEFAULT_REGION: ap-south-1
  AWS_DEFAULT_OUTPUT: json

# for creating buckets voth region shouldd be same else says request send to wrong endpoint !!

jobs:
  verify-vars:
    runs-on: ubuntu-latest
    steps:
      - name: verify vars
        run: |
          echo "s3=$s3 and region=$region" || echo "no variables defined !!!"
          
      - name: dir
        run: |
          echo "${{ github.workspace }}"
          
          MY_WORK_DIR="${{ github.workspace }}"
          echo "MY_WORK_DIR=$MY_WORK_DIR" >> $GITHUB_ENV
          
      - name: List files in workspace
        run: |
          echo "Current directory: $(pwd)"
          ls -l "${{ github.workspace }}"

  build-and-deploy:
    needs: verify-vars
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
    
    - name: Create s3 bucket
      run: |
        aws s3 mb s3://$s3 --region $region
      continue-on-error: true
    
    - name: Attach s3 bucket policy 
      run: aws s3api put-bucket-policy --bucket $s3 --policy file://policy.json
      working-directory: ${{ github.workspace }}/DevOps

    - name: Provision s3 website
      run: |
          aws s3 website s3://$s3/ \
          --index-document index.html \
          --error-document error.html

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://$s3 --delete
