name: myown

on:
  push:
    branches:
    - main

env:
  s3: my-own-aws742
  region: ap-south-1

jobs:
  verify-vars:
    runs-on: ubuntu-latest
    steps:
     - name: verify vars
       run: echo $s3 and $region || echo "no variables defined !!!"
       
  build-and-deploy:
    needs: verify-vars
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $region
    
    - name: Create s3 bucket
      run: |
        aws s3api create-bucket \
        --bucket $s3 \
        --region $region
    
    - name: Attach s3 bucket policy 
      run: aws s3api put-bucket-policy --bucket $s3 --policy file://policy.json

    - name: Provision s3 website
      run: |
          aws s3 website s3://$s3/ \
          --index-document index.html \
          --error-document error.html

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://$s3 --delete
