# The workflow Creates static website using aws s3
name: AWS OIDC workflow
on:
  push
env:
  BUCKET_NAME : "assignment-dev-env-tfstate "
  AWS_REGION : "ap-south-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.0.2   
        with:
          role-to-assume: arn:aws:iam::654654187843:role/github-oidc
          role-session-name: gh-oidc
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Deploy static site to S3 bucket
      #run: aws s3 sync ./DevOps s3://kk-songs984 --delete
        run: aws s3 sync ./DevOps s3://${{ env.BUCKET_NAME }} --delete --exclude "*.md" 
